import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ArrowLeft, KeyRound, Eye, EyeOff, ShieldAlert, CheckCircle2 } from 'lucide-react'
import PageHeader from '../../components/common/PageHeader'
import Card from '../../components/common/Card'
import Input from '../../components/common/Input'
import Button from '../../components/common/Button'
import { useAuth } from '../../context/AuthContext'
import { useToast } from '../../context/ToastContext'

function ChangePassword() {
  const { user, changePassword } = useAuth()
  const { showToast } = useToast()
  const navigate = useNavigate()

  const [values, setValues] = useState({ current: '', newPassword: '', confirm: '' })
  const [errors, setErrors] = useState({})
  const [show, setShow] = useState({ current: false, newPassword: false, confirm: false })
  const [submitting, setSubmitting] = useState(false)

  const isMandatoryFirstLogin = Boolean(user?.mustChangePassword)

  const toggleShow = (field) => {
    setShow((prev) => ({ ...prev, [field]: !prev[field] }))
  }

  const handleChange = (event) => {
    const { name, value } = event.target
    setValues((prev) => ({ ...prev, [name]: value }))
    if (errors[name]) setErrors((prev) => ({ ...prev, [name]: '' }))
  }

  const handleSubmit = async (event) => {
    event.preventDefault()
    const nextErrors = {}
    if (!values.current) nextErrors.current = 'Current password is required'
    if (!values.newPassword) nextErrors.newPassword = 'New password is required'
    else if (values.newPassword.length < 6) nextErrors.newPassword = 'Password must be at least 6 characters'
    if (!values.confirm) nextErrors.confirm = 'Confirm your new password'
    else if (values.newPassword !== values.confirm) nextErrors.confirm = 'Passwords do not match'

    setErrors(nextErrors)
    if (Object.keys(nextErrors).length) return

    setSubmitting(true)
    const result = await changePassword(values.current, values.newPassword)
    setSubmitting(false)

    if (result.ok) {
      showToast('Password changed successfully! You now have full access to your portal.', 'success')
      navigate('/dashboard')
    } else {
      showToast(result.error || 'Failed to change password', 'error')
      setErrors({ current: result.error })
    }
  }

  const renderPasswordInput = (name, label, placeholder) => (
    <div className="relative">
      <Input
        label={label}
        type={show[name] ? 'text' : 'password'}
        name={name}
        value={values[name]}
        onChange={handleChange}
        error={errors[name]}
        required
        placeholder={placeholder}
        autoComplete="off"
        className="pr-11"
      />
      <button
        type="button"
        onClick={() => toggleShow(name)}
        className="absolute top-[38px] right-3 text-slate-400 transition hover:text-slate-600 cursor-pointer"
        aria-label={`${show[name] ? 'Hide' : 'Show'} ${label}`}
      >
        {show[name] ? <EyeOff size={18} /> : <Eye size={18} />}
      </button>
    </div>
  )

  return (
    <div className="space-y-6 animate-fade-in">
      <PageHeader
        title={isMandatoryFirstLogin ? 'First Login: Change Temporary Password' : 'Change Password'}
        description={
          isMandatoryFirstLogin
            ? 'For security reasons, you must set a new permanent password before accessing your academy dashboard.'
            : 'Update the password for your account'
        }
        breadcrumb={[
          { label: 'Profile', href: '/profile' },
          { label: 'Change Password' },
        ]}
        actions={
          !isMandatoryFirstLogin && (
            <Link to="/profile">
              <Button variant="outline" leftIcon={ArrowLeft}>Back to Profile</Button>
            </Link>
          )
        }
      />

      {isMandatoryFirstLogin && (
        <div className="max-w-2xl rounded-2xl bg-amber-50 border border-amber-200/80 p-4 text-amber-900 flex items-start gap-3 shadow-xs">
          <ShieldAlert size={22} className="text-amber-600 shrink-0 mt-0.5" />
          <div className="text-xs space-y-1">
            <p className="font-bold text-amber-950 text-sm">Security Notice: Temporary Password Active</p>
            <p className="text-amber-800 leading-relaxed">
              Your account was created with a temporary password generated by the administration.
              Please establish your new, confidential password below. Once saved, you will immediately be directed to your {user?.role || ''} dashboard.
            </p>
          </div>
        </div>
      )}

      <form onSubmit={handleSubmit}>
        <Card className="max-w-2xl">
          <h3 className="mb-4 border-b border-slate-100 pb-3 text-sm font-semibold tracking-wide text-slate-500 uppercase flex items-center gap-2">
            <KeyRound size={18} className="text-purple-600" />
            Password Credentials
          </h3>

          <div className="grid grid-cols-1 gap-4">
            {renderPasswordInput('current', 'Current (Temporary) Password', 'Enter current or temporary password')}
            {renderPasswordInput('newPassword', 'New Password', 'Enter new secure password (min 6 characters)')}
            {renderPasswordInput('confirm', 'Confirm New Password', 'Re-enter your new password')}
          </div>

          <div className="mt-6 flex justify-end gap-3 border-t border-slate-100 pt-4">
            {!isMandatoryFirstLogin && (
              <Link to="/profile">
                <Button type="button" variant="outline">Cancel</Button>
              </Link>
            )}
            <Button
              type="submit"
              variant="primary"
              loading={submitting}
              leftIcon={CheckCircle2}
              className="bg-purple-600 hover:bg-purple-700"
            >
              Save New Password & Continue
            </Button>
          </div>
        </Card>
      </form>
    </div>
  )
}

export default ChangePassword
